main: onevnl.ru.elytrya.BoostyBridge
version: b0.3
name: BoostyBridge
author: elytrya
api-version: 1.16

softdepend: [PlaceholderAPI]

commands:
  boosty:
    description: /boosty help

permissions:
  boosty.link:
    description: /boosty link - привязка аккаунта
    default: true
  boosty.info:
    description: /boosty info - инфо
    default: true
  boosty.discord:
    description: /boosty discord - привязка Discord аккаунта для получения ролей
    default: true
  boosty.reload:
    description: /boosty reload - релоад плагина
    default: op
  boosty.admin.unlink:
    description: /boosty admin unlink - админ, отвязка аккаунта
    default: op
  boosty.admin.info:
    description: /boosty admin info - админ, инфо о аккаунте игрока
    default: op
  boosty.admin.forcelink:
    description: /boosty admin forcelink - админ, привязка аккаунта
    default: op
  boosty.admin.forcesync:
    description: /boosty admin forcesync - админ, синхорнизация
    default: op
  boosty.admin.setdiscord:
    description: "/boosty admin setdiscord - админ, сет дискорда"
    default: op
  boosty.admin.*:
    description: /boosty admin *
    default: op
    children:
      boosty.reload: true
      boosty.admin.unlink: true
      boosty.admin.info: true
      boosty.admin.forcelink: true
      boosty.admin.forcesync: true
      boosty.admin.setdiscord: true
  boosty.*:
    description: все права
    default: op
    children:
      boosty.link: true
      boosty.info: true
      boosty.admin.*: true
